source "http://api.berkshelf.com"

cookbook "apt"
cookbook "build-essential"
cookbook "curl"
cookbook "git"
cookbook "libqt4"
cookbook "libsasl2_dev", path: "kitchen/site-cookbooks/libsasl2_dev"
cookbook "nodejs"
cookbook "openssl"
cookbook "phantomjs"
cookbook "python"
cookbook "ruby_dev", path: "kitchen/site-cookbooks/ruby_dev"
cookbook "rvm"
